### ISSUE TITLE
"typescript": "^1.7.5"

### ISSUE THREAD

**Issue by webonix** [Gajotres/Ionic2RESTHttpExample#1]
I hope this means something to you and helps out

based on this

> https://github.com/driftyco/ionic/issues/5264

I removed carets from package.json
  "devDependencies": {
    "awesome-typescript-loader": "^0.15.9",
    "strip-sourcemap-loader": "0.0.1",
    "typescript": "^1.7.5"
  },

to get past this error

```
./app/app.js
Module build failed: Error: Emit skipped
    at State.emit (C:\websites\ionic2\Ionic2RESTHttpExample\node_modules\awesome-typescript-loader\dist.babel\host.js:260:23)
    at transform (C:\websites\ionic2\Ionic2RESTHttpExample\node_modules\awesome-typescript-loader\dist.babel\index.js:163:48)
    at _callee2$ (C:\websites\ionic2\Ionic2RESTHttpExample\node_modules\awesome-typescript-loader\dist.babel\index.js:213:42)
    at tryCatch (C:\websites\ionic2\Ionic2RESTHttpExample\node_modules\awesome-typescript-loader\node_modules\babel-polyfill\node_mo
dules\babel-regenerator-runtime\runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\websites\ionic2\Ionic2RESTHttpExample\node_modules\awesome-typescript-load
er\node_modules\babel-polyfill\node_modules\babel-regenerator-runtime\runtime.js:329:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\websites\ionic2\Ionic2RESTHttpExample\node_modules\aw
esome-typescript-loader\node_modules\babel-polyfill\node_modules\babel-regenerator-runtime\runtime.js:94:21)
    at fulfilled (C:\websites\ionic2\Ionic2RESTHttpExample\node_modules\awesome-typescript-loader\dist.babel\index.js:11:32)
    at tryCatcher (C:\websites\ionic2\Ionic2RESTHttpExample\node_modules\awesome-typescript-loader\node_modules\bluebird\js\main\uti
l.js:26:23)
    at Promise._settlePromiseFromHandler (C:\websites\ionic2\Ionic2RESTHttpExample\node_modules\awesome-typescript-loader\node_modul
es\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\websites\ionic2\Ionic2RESTHttpExample\node_modules\awesome-typescript-loader\node_modules\bluebi
rd\js\main\promise.js:581:18)
    at Async._drainQueue (C:\websites\ionic2\Ionic2RESTHttpExample\node_modules\awesome-typescript-loader\node_modules\bluebird\js\m
ain\async.js:128:12)
    at Async._drainQueues (C:\websites\ionic2\Ionic2RESTHttpExample\node_modules\awesome-typescript-loader\node_modules\bluebird\js\
main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\websites\ionic2\Ionic2RESTHttpExample\node_modules\awesome-typescript-loade
r\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
 @ multi main (CLI v2.0.0-beta.19)
```

**Comment by Gajotres** [comment]
Demo example has been updated to Ionic 2.2.1
